name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: init/
      - name: Get Version
        id: get_version
        run: |
          cd init
          version=$(grep '^version =' Cargo.toml | head -n1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "# Init Summary" >> $GITHUB_STEP_SUMMARY
          echo "Found package version: $version"  >> $GITHUB_STEP_SUMMARY

  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: deploy/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: deploy/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.init.outputs.version }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
