name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: init/
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt install libwebkit2gtk-4.1-dev -y
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - name: Get Version
        id: get_version
        run: |
          cd init
          cargo build
          echo "version=$(cargo pkgid | cut -d "@" -f2)" >> "$GITHUB_OUTPUT"
          echo "# Init Summary" >> $GITHUB_STEP_SUMMARY
          echo "Found package version: $(cargo pkgid | cut -d "@" -f2)"  >> $GITHUB_STEP_SUMMARY

  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: deploy/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: deploy/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.init.outputs.version }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
